export interface Country {
  name_es: string;
  name_en: string;
  iso2: string;
  iso3: string;
}

export const UN_195_COUNTRIES: Country[] = [
  { name_es: "Afganistán", name_en: "Afghanistan", iso2: "AF", iso3: "AFG" },
  { name_es: "Albania", name_en: "Albania", iso2: "AL", iso3: "ALB" },
  { name_es: "Alemania", name_en: "Germany", iso2: "DE", iso3: "DEU" },
  { name_es: "Andorra", name_en: "Andorra", iso2: "AD", iso3: "AND" },
  { name_es: "Angola", name_en: "Angola", iso2: "AO", iso3: "AGO" },
  { name_es: "Antigua y Barbuda", name_en: "Antigua and Barbuda", iso2: "AG", iso3: "ATG" },
  { name_es: "Arabia Saudita", name_en: "Saudi Arabia", iso2: "SA", iso3: "SAU" },
  { name_es: "Argelia", name_en: "Algeria", iso2: "DZ", iso3: "DZA" },
  { name_es: "Argentina", name_en: "Argentina", iso2: "AR", iso3: "ARG" },
  { name_es: "Armenia", name_en: "Armenia", iso2: "AM", iso3: "ARM" },
  { name_es: "Australia", name_en: "Australia", iso2: "AU", iso3: "AUS" },
  { name_es: "Austria", name_en: "Austria", iso2: "AT", iso3: "AUT" },
  { name_es: "Azerbaiyán", name_en: "Azerbaijan", iso2: "AZ", iso3: "AZE" },
  { name_es: "Bahamas", name_en: "Bahamas", iso2: "BS", iso3: "BHS" },
  { name_es: "Baréin", name_en: "Bahrain", iso2: "BH", iso3: "BHR" },
  { name_es: "Bangladés", name_en: "Bangladesh", iso2: "BD", iso3: "BGD" },
  { name_es: "Barbados", name_en: "Barbados", iso2: "BB", iso3: "BRB" },
  { name_es: "Bélgica", name_en: "Belgium", iso2: "BE", iso3: "BEL" },
  { name_es: "Belice", name_en: "Belize", iso2: "BZ", iso3: "BLZ" },
  { name_es: "Benín", name_en: "Benin", iso2: "BJ", iso3: "BEN" },
  { name_es: "Bielorrusia", name_en: "Belarus", iso2: "BY", iso3: "BLR" },
  { name_es: "Birmania", name_en: "Myanmar", iso2: "MM", iso3: "MMR" },
  { name_es: "Bolivia", name_en: "Bolivia", iso2: "BO", iso3: "BOL" },
  { name_es: "Bosnia y Herzegovina", name_en: "Bosnia and Herzegovina", iso2: "BA", iso3: "BIH" },
  { name_es: "Botsuana", name_en: "Botswana", iso2: "BW", iso3: "BWA" },
  { name_es: "Brasil", name_en: "Brazil", iso2: "BR", iso3: "BRA" },
  { name_es: "Brunéi", name_en: "Brunei", iso2: "BN", iso3: "BRN" },
  { name_es: "Bulgaria", name_en: "Bulgaria", iso2: "BG", iso3: "BGR" },
  { name_es: "Burkina Faso", name_en: "Burkina Faso", iso2: "BF", iso3: "BFA" },
  { name_es: "Burundi", name_en: "Burundi", iso2: "BI", iso3: "BDI" },
  { name_es: "Bután", name_en: "Bhutan", iso2: "BT", iso3: "BTN" },
  { name_es: "Cabo Verde", name_en: "Cape Verde", iso2: "CV", iso3: "CPV" },
  { name_es: "Camboya", name_en: "Cambodia", iso2: "KH", iso3: "KHM" },
  { name_es: "Camerún", name_en: "Cameroon", iso2: "CM", iso3: "CMR" },
  { name_es: "Canadá", name_en: "Canada", iso2: "CA", iso3: "CAN" },
  { name_es: "Catar", name_en: "Qatar", iso2: "QA", iso3: "QAT" },
  { name_es: "Chad", name_en: "Chad", iso2: "TD", iso3: "TCD" },
  { name_es: "Chile", name_en: "Chile", iso2: "CL", iso3: "CHL" },
  { name_es: "China", name_en: "China", iso2: "CN", iso3: "CHN" },
  { name_es: "Chipre", name_en: "Cyprus", iso2: "CY", iso3: "CYP" },
  { name_es: "Colombia", name_en: "Colombia", iso2: "CO", iso3: "COL" },
  { name_es: "Comoras", name_en: "Comoros", iso2: "KM", iso3: "COM" },
  { name_es: "Congo", name_en: "Congo", iso2: "CG", iso3: "COG" },
  { name_es: "Corea del Norte", name_en: "North Korea", iso2: "KP", iso3: "PRK" },
  { name_es: "Corea del Sur", name_en: "South Korea", iso2: "KR", iso3: "KOR" },
  { name_es: "Costa de Marfil", name_en: "Ivory Coast", iso2: "CI", iso3: "CIV" },
  { name_es: "Costa Rica", name_en: "Costa Rica", iso2: "CR", iso3: "CRI" },
  { name_es: "Croacia", name_en: "Croatia", iso2: "HR", iso3: "HRV" },
  { name_es: "Cuba", name_en: "Cuba", iso2: "CU", iso3: "CUB" },
  { name_es: "Dinamarca", name_en: "Denmark", iso2: "DK", iso3: "DNK" },
  { name_es: "Dominica", name_en: "Dominica", iso2: "DM", iso3: "DMA" },
  { name_es: "Ecuador", name_en: "Ecuador", iso2: "EC", iso3: "ECU" },
  { name_es: "Egipto", name_en: "Egypt", iso2: "EG", iso3: "EGY" },
  { name_es: "El Salvador", name_en: "El Salvador", iso2: "SV", iso3: "SLV" },
  { name_es: "Emiratos Árabes Unidos", name_en: "United Arab Emirates", iso2: "AE", iso3: "ARE" },
  { name_es: "Eritrea", name_en: "Eritrea", iso2: "ER", iso3: "ERI" },
  { name_es: "Eslovaquia", name_en: "Slovakia", iso2: "SK", iso3: "SVK" },
  { name_es: "Eslovenia", name_en: "Slovenia", iso2: "SI", iso3: "SVN" },
  { name_es: "España", name_en: "Spain", iso2: "ES", iso3: "ESP" },
  { name_es: "Estados Unidos", name_en: "United States", iso2: "US", iso3: "USA" },
  { name_es: "Estonia", name_en: "Estonia", iso2: "EE", iso3: "EST" },
  { name_es: "Esuatini", name_en: "Eswatini", iso2: "SZ", iso3: "SWZ" },
  { name_es: "Etiopía", name_en: "Ethiopia", iso2: "ET", iso3: "ETH" },
  { name_es: "Filipinas", name_en: "Philippines", iso2: "PH", iso3: "PHL" },
  { name_es: "Finlandia", name_en: "Finland", iso2: "FI", iso3: "FIN" },
  { name_es: "Fiyi", name_en: "Fiji", iso2: "FJ", iso3: "FJI" },
  { name_es: "Francia", name_en: "France", iso2: "FR", iso3: "FRA" },
  { name_es: "Gabón", name_en: "Gabon", iso2: "GA", iso3: "GAB" },
  { name_es: "Gambia", name_en: "Gambia", iso2: "GM", iso3: "GMB" },
  { name_es: "Georgia", name_en: "Georgia", iso2: "GE", iso3: "GEO" },
  { name_es: "Ghana", name_en: "Ghana", iso2: "GH", iso3: "GHA" },
  { name_es: "Granada", name_en: "Grenada", iso2: "GD", iso3: "GRD" },
  { name_es: "Grecia", name_en: "Greece", iso2: "GR", iso3: "GRC" },
  { name_es: "Guatemala", name_en: "Guatemala", iso2: "GT", iso3: "GTM" },
  { name_es: "Guinea", name_en: "Guinea", iso2: "GN", iso3: "GIN" },
  { name_es: "Guinea-Bisáu", name_en: "Guinea-Bissau", iso2: "GW", iso3: "GNB" },
  { name_es: "Guinea Ecuatorial", name_en: "Equatorial Guinea", iso2: "GQ", iso3: "GNQ" },
  { name_es: "Guyana", name_en: "Guyana", iso2: "GY", iso3: "GUY" },
  { name_es: "Haití", name_en: "Haiti", iso2: "HT", iso3: "HTI" },
  { name_es: "Honduras", name_en: "Honduras", iso2: "HN", iso3: "HND" },
  { name_es: "Hungría", name_en: "Hungary", iso2: "HU", iso3: "HUN" },
  { name_es: "India", name_en: "India", iso2: "IN", iso3: "IND" },
  { name_es: "Indonesia", name_en: "Indonesia", iso2: "ID", iso3: "IDN" },
  { name_es: "Irak", name_en: "Iraq", iso2: "IQ", iso3: "IRQ" },
  { name_es: "Irán", name_en: "Iran", iso2: "IR", iso3: "IRN" },
  { name_es: "Irlanda", name_en: "Ireland", iso2: "IE", iso3: "IRL" },
  { name_es: "Islandia", name_en: "Iceland", iso2: "IS", iso3: "ISL" },
  { name_es: "Islas Marshall", name_en: "Marshall Islands", iso2: "MH", iso3: "MHL" },
  { name_es: "Islas Salomón", name_en: "Solomon Islands", iso2: "SB", iso3: "SLB" },
  { name_es: "Israel", name_en: "Israel", iso2: "IL", iso3: "ISR" },
  { name_es: "Italia", name_en: "Italy", iso2: "IT", iso3: "ITA" },
  { name_es: "Jamaica", name_en: "Jamaica", iso2: "JM", iso3: "JAM" },
  { name_es: "Japón", name_en: "Japan", iso2: "JP", iso3: "JPN" },
  { name_es: "Jordania", name_en: "Jordan", iso2: "JO", iso3: "JOR" },
  { name_es: "Kazajistán", name_en: "Kazakhstan", iso2: "KZ", iso3: "KAZ" },
  { name_es: "Kenia", name_en: "Kenya", iso2: "KE", iso3: "KEN" },
  { name_es: "Kirguistán", name_en: "Kyrgyzstan", iso2: "KG", iso3: "KGZ" },
  { name_es: "Kiribati", name_en: "Kiribati", iso2: "KI", iso3: "KIR" },
  { name_es: "Kuwait", name_en: "Kuwait", iso2: "KW", iso3: "KWT" },
  { name_es: "Laos", name_en: "Laos", iso2: "LA", iso3: "LAO" },
  { name_es: "Lesoto", name_en: "Lesotho", iso2: "LS", iso3: "LSO" },
  { name_es: "Letonia", name_en: "Latvia", iso2: "LV", iso3: "LVA" },
  { name_es: "Líbano", name_en: "Lebanon", iso2: "LB", iso3: "LBN" },
  { name_es: "Liberia", name_en: "Liberia", iso2: "LR", iso3: "LBR" },
  { name_es: "Libia", name_en: "Libya", iso2: "LY", iso3: "LBY" },
  { name_es: "Liechtenstein", name_en: "Liechtenstein", iso2: "LI", iso3: "LIE" },
  { name_es: "Lituania", name_en: "Lithuania", iso2: "LT", iso3: "LTU" },
  { name_es: "Luxemburgo", name_en: "Luxembourg", iso2: "LU", iso3: "LUX" },
  { name_es: "Macedonia del Norte", name_en: "North Macedonia", iso2: "MK", iso3: "MKD" },
  { name_es: "Madagascar", name_en: "Madagascar", iso2: "MG", iso3: "MDG" },
  { name_es: "Malasia", name_en: "Malaysia", iso2: "MY", iso3: "MYS" },
  { name_es: "Malaui", name_en: "Malawi", iso2: "MW", iso3: "MWI" },
  { name_es: "Maldivas", name_en: "Maldives", iso2: "MV", iso3: "MDV" },
  { name_es: "Malí", name_en: "Mali", iso2: "ML", iso3: "MLI" },
  { name_es: "Malta", name_en: "Malta", iso2: "MT", iso3: "MLT" },
  { name_es: "Marruecos", name_en: "Morocco", iso2: "MA", iso3: "MAR" },
  { name_es: "Mauricio", name_en: "Mauritius", iso2: "MU", iso3: "MUS" },
  { name_es: "Mauritania", name_en: "Mauritania", iso2: "MR", iso3: "MRT" },
  { name_es: "México", name_en: "Mexico", iso2: "MX", iso3: "MEX" },
  { name_es: "Micronesia", name_en: "Micronesia", iso2: "FM", iso3: "FSM" },
  { name_es: "Moldavia", name_en: "Moldova", iso2: "MD", iso3: "MDA" },
  { name_es: "Mónaco", name_en: "Monaco", iso2: "MC", iso3: "MCO" },
  { name_es: "Mongolia", name_en: "Mongolia", iso2: "MN", iso3: "MNG" },
  { name_es: "Montenegro", name_en: "Montenegro", iso2: "ME", iso3: "MNE" },
  { name_es: "Mozambique", name_en: "Mozambique", iso2: "MZ", iso3: "MOZ" },
  { name_es: "Namibia", name_en: "Namibia", iso2: "NA", iso3: "NAM" },
  { name_es: "Nauru", name_en: "Nauru", iso2: "NR", iso3: "NRU" },
  { name_es: "Nepal", name_en: "Nepal", iso2: "NP", iso3: "NPL" },
  { name_es: "Nicaragua", name_en: "Nicaragua", iso2: "NI", iso3: "NIC" },
  { name_es: "Níger", name_en: "Niger", iso2: "NE", iso3: "NER" },
  { name_es: "Nigeria", name_en: "Nigeria", iso2: "NG", iso3: "NGA" },
  { name_es: "Noruega", name_en: "Norway", iso2: "NO", iso3: "NOR" },
  { name_es: "Nueva Zelanda", name_en: "New Zealand", iso2: "NZ", iso3: "NZL" },
  { name_es: "Omán", name_en: "Oman", iso2: "OM", iso3: "OMN" },
  { name_es: "Países Bajos", name_en: "Netherlands", iso2: "NL", iso3: "NLD" },
  { name_es: "Pakistán", name_en: "Pakistan", iso2: "PK", iso3: "PAK" },
  { name_es: "Palaos", name_en: "Palau", iso2: "PW", iso3: "PLW" },
  { name_es: "Panamá", name_en: "Panama", iso2: "PA", iso3: "PAN" },
  { name_es: "Papúa Nueva Guinea", name_en: "Papua New Guinea", iso2: "PG", iso3: "PNG" },
  { name_es: "Paraguay", name_en: "Paraguay", iso2: "PY", iso3: "PRY" },
  { name_es: "Perú", name_en: "Peru", iso2: "PE", iso3: "PER" },
  { name_es: "Polonia", name_en: "Poland", iso2: "PL", iso3: "POL" },
  { name_es: "Portugal", name_en: "Portugal", iso2: "PT", iso3: "PRT" },
  { name_es: "Reino Unido", name_en: "United Kingdom", iso2: "GB", iso3: "GBR" },
  { name_es: "República Centroafricana", name_en: "Central African Republic", iso2: "CF", iso3: "CAF" },
  { name_es: "República Checa", name_en: "Czech Republic", iso2: "CZ", iso3: "CZE" },
  { name_es: "República del Congo", name_en: "Democratic Republic of the Congo", iso2: "CD", iso3: "COD" },
  { name_es: "República Dominicana", name_en: "Dominican Republic", iso2: "DO", iso3: "DOM" },
  { name_es: "Ruanda", name_en: "Rwanda", iso2: "RW", iso3: "RWA" },
  { name_es: "Rumanía", name_en: "Romania", iso2: "RO", iso3: "ROU" },
  { name_es: "Rusia", name_en: "Russia", iso2: "RU", iso3: "RUS" },
  { name_es: "Samoa", name_en: "Samoa", iso2: "WS", iso3: "WSM" },
  { name_es: "San Cristóbal y Nieves", name_en: "Saint Kitts and Nevis", iso2: "KN", iso3: "KNA" },
  { name_es: "San Marino", name_en: "San Marino", iso2: "SM", iso3: "SMR" },
  { name_es: "San Vicente y las Granadinas", name_en: "Saint Vincent and the Grenadines", iso2: "VC", iso3: "VCT" },
  { name_es: "Santa Lucía", name_en: "Saint Lucia", iso2: "LC", iso3: "LCA" },
  { name_es: "Santo Tomé y Príncipe", name_en: "Sao Tome and Principe", iso2: "ST", iso3: "STP" },
  { name_es: "Senegal", name_en: "Senegal", iso2: "SN", iso3: "SEN" },
  { name_es: "Serbia", name_en: "Serbia", iso2: "RS", iso3: "SRB" },
  { name_es: "Seychelles", name_en: "Seychelles", iso2: "SC", iso3: "SYC" },
  { name_es: "Sierra Leona", name_en: "Sierra Leone", iso2: "SL", iso3: "SLE" },
  { name_es: "Singapur", name_en: "Singapore", iso2: "SG", iso3: "SGP" },
  { name_es: "Siria", name_en: "Syria", iso2: "SY", iso3: "SYR" },
  { name_es: "Somalia", name_en: "Somalia", iso2: "SO", iso3: "SOM" },
  { name_es: "Sri Lanka", name_en: "Sri Lanka", iso2: "LK", iso3: "LKA" },
  { name_es: "Sudáfrica", name_en: "South Africa", iso2: "ZA", iso3: "ZAF" },
  { name_es: "Sudán", name_en: "Sudan", iso2: "SD", iso3: "SDN" },
  { name_es: "Sudán del Sur", name_en: "South Sudan", iso2: "SS", iso3: "SSD" },
  { name_es: "Suecia", name_en: "Sweden", iso2: "SE", iso3: "SWE" },
  { name_es: "Suiza", name_en: "Switzerland", iso2: "CH", iso3: "CHE" },
  { name_es: "Surinam", name_en: "Suriname", iso2: "SR", iso3: "SUR" },
  { name_es: "Tailandia", name_en: "Thailand", iso2: "TH", iso3: "THA" },
  { name_es: "Tanzania", name_en: "Tanzania", iso2: "TZ", iso3: "TZA" },
  { name_es: "Tayikistán", name_en: "Tajikistan", iso2: "TJ", iso3: "TJK" },
  { name_es: "Timor Oriental", name_en: "East Timor", iso2: "TL", iso3: "TLS" },
  { name_es: "Togo", name_en: "Togo", iso2: "TG", iso3: "TGO" },
  { name_es: "Tonga", name_en: "Tonga", iso2: "TO", iso3: "TON" },
  { name_es: "Trinidad y Tobago", name_en: "Trinidad and Tobago", iso2: "TT", iso3: "TTO" },
  { name_es: "Túnez", name_en: "Tunisia", iso2: "TN", iso3: "TUN" },
  { name_es: "Turkmenistán", name_en: "Turkmenistan", iso2: "TM", iso3: "TKM" },
  { name_es: "Turquía", name_en: "Turkey", iso2: "TR", iso3: "TUR" },
  { name_es: "Tuvalu", name_en: "Tuvalu", iso2: "TV", iso3: "TUV" },
  { name_es: "Ucrania", name_en: "Ukraine", iso2: "UA", iso3: "UKR" },
  { name_es: "Uganda", name_en: "Uganda", iso2: "UG", iso3: "UGA" },
  { name_es: "Uruguay", name_en: "Uruguay", iso2: "UY", iso3: "URY" },
  { name_es: "Uzbekistán", name_en: "Uzbekistan", iso2: "UZ", iso3: "UZB" },
  { name_es: "Vanuatu", name_en: "Vanuatu", iso2: "VU", iso3: "VUT" },
  { name_es: "Vaticano", name_en: "Vatican City", iso2: "VA", iso3: "VAT" },
  { name_es: "Venezuela", name_en: "Venezuela", iso2: "VE", iso3: "VEN" },
  { name_es: "Vietnam", name_en: "Vietnam", iso2: "VN", iso3: "VNM" },
  { name_es: "Yemen", name_en: "Yemen", iso2: "YE", iso3: "YEM" },
  { name_es: "Yibuti", name_en: "Djibouti", iso2: "DJ", iso3: "DJI" },
  { name_es: "Zambia", name_en: "Zambia", iso2: "ZM", iso3: "ZMB" },
  { name_es: "Zimbabue", name_en: "Zimbabwe", iso2: "ZW", iso3: "ZWE" },
];
